### ISSUE TITLE
ROS release of message_logger

### ISSUE THREAD

**Issue by mikekaram** [ANYbotics/message_logger#1]
Hello,

we want to release a ROS package which depends on `message_logger`. I created a [repo](https://github.com/mikekaram/message_logger-release) to release message_logger into ROS. However, I really think that this repo belongs under the Anybotics roof. If there is an issue with this move, please let me know.

Cheers,
Mike

**Comment by remod** [comment]
Hi Mike

The `message_logger` and `any_node` packages are both abstractions for ROS 1 functionalities. As we will migrate to ROS 2 soon, we will deprecate both packages, meaning that we will stop maintaining the packages and not be able to give support anymore.

Therefore we don't want to release the packages officially at this point.

You are free to release the packages yourself though.

Thanks for your understanding,
Remo
