### ISSUE TITLE
Updated package.xml

### ISSUE THREAD

**Issue by FrederikBark** [ANYbotics/message_logger#2]
Hello, 

It seems like your update from yesterday added new dependencies to the package.xml:

anymal_sentry_native
sentry_native

As these packages don't seem to be public on your Github, it is not possible for us to build this package. Is this just an oversight from your side, or is this intended to be a permanent change?

**Comment by remod** [comment]
Thanks for reporting @TheMangalex !

We've fixed the code snychronization, now the internal dependencies are commented out.
